### ISSUE TITLE
Could not resolve com.razorpay:checkout:1.6.+.

### ISSUE THREAD

**Issue by nimesh-devloper** [razorpay/razorpay-flutter#403] opened 2024-08-13 05:50 UTC
* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve com.razorpay:checkout:1.6.+.
     Required by:
         project :app > project :razorpay_flutter
      > Failed to list versions for com.razorpay:checkout.
         > Unable to load Maven meta-data from https://jcenter.bintray.com/com/razorpay/checkout/maven-metadata.xml.
            > Could not HEAD 'https://jcenter.bintray.com/com/razorpay/checkout/maven-metadata.xml'. Received status code 500 from server: Internal Server Error

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 15s
Error: Gradle task assembleDebug failed with exit code 1

I am getting this issue, can you please tell us how I can solve this issue?

**Comment by Sobitandra** [comment] 2024-08-13 05:52
I am also facing the same issue.

**Comment by kavinezee** [comment] 2024-08-13 05:56
I'm also facing the same issue. If someone find the solution please pin me to

**Comment by Vikas1498** [comment] 2024-08-13 06:05
I'm experiencing the same issue. If anyone finds a solution, please let me know so I can explore it further.

**Comment by sachindarde** [comment] 2024-08-13 06:07
To effectively report this issue on GitHub, you can structure your post as follows:

---

### Issue: Razorpay Checkout Maven Repository Unavailable

#### Description:
The Maven metadata file for Razorpay's checkout library hosted at `https://jcenter.bintray.com/com/razorpay/checkout/maven-metadata.xml` appears to be down. When attempting to access or retrieve dependencies, the following error is encountered:

```
Failed to resolve: com.razorpay:checkout:<version>
```

#### Steps to Reproduce:
1. Include the Razorpay Checkout dependency in your `build.gradle` file:
   ```gradle
   implementation 'com.razorpay:checkout:<version>'
   ```
2. Attempt to sync or build the project.
3. Observe the failure due to the unavailability of the Maven repository.

#### Expected Behavior:
The repository should be accessible, allowing for successful dependency resolution.

#### Actual Behavior:
Accessing the URL `https://jcenter.bintray.com/com/razorpay/checkout/maven-metadata.xml` results in an error, and the dependency cannot be resolved.

#### Screenshot:
![Error Screenshot](https://github.com/user-attachments/assets/06be3306-b7c0-40bf-a635-54fa083c09a3)

#### Additional Context:
Please provide guidance on how to resolve this issue, or suggest an alternative repository or method to include the Razorpay Checkout library in the project.

**Comment by wrteam-vimal** [comment] 2024-08-13 06:10
Same issue here

**Comment by SumitRayte** [comment] 2024-08-13 06:11
Same issue here. I am not able proceed further. If anyone finds a solution, please let me know.

**Comment by vivekshindhe** [comment] 2024-08-13 06:20
Hey folks, the issue is not with the razorpay-checkout SDK but with mavenCentral. The razorpay-flutter package does not use jcenter. You can verify this [here](https://github.com/razorpay/razorpay-flutter/blob/b/namespace-fix-flutter/android/build.gradle). Also attaching the [link](https://status.maven.org/) to the site which states the outage in OSSRH (mavenCentral) which is why we are seeing this issue. The issue is also different for each because using a specific version has been working for some folks, while it hasn’t for others. You can try to use https://github.com/razorpay/razorpay-flutter/issues/400#issuecomment-2285365867 (Thank you @niladri-raychaudhuri for explaining the steps) fix temporarily to see if that would resolve it for you, while we look into resolving this from our end.

**Comment by vivekshindhe** [comment] 2024-08-13 06:32
Hey folks, seems like the issue on mavenCentral is resolved. You can check the latest status [here](https://status.maven.org/). Please try to run ./gradlew --refresh-dependencies or ./gradle --refresh-dependencies or run Sync project with Gradle files in Android studio when the android project is opened.

**Comment by nimesh-devloper** [comment] 2024-08-13 06:40
Hey folks, 

I think Maven Central has resolved this issue, now just run the **flutter clean** and **flutter pub get** commands in your Terminal and it will work again.

**Closed** 2024-08-13 06:41 UTC
