### ISSUE TITLE
Payment Gateway response successfull even when i cancelled the payment ?

### ISSUE THREAD

**Issue by JayM96** [razorpay/razorpay-flutter#39] opened 2019-10-16 11:51 UTC
Hello,

#Issue - 1
 
I have implemented the code described on official plugin package. but, when i test with my testkey and when i click on pay button and try to pay with googlepay. after then click on pay button.

Then if i do not complete the payment and click on back button it says payment successful. 
Even it is showing on the razorpay dashboard.

Can you please help me to resolve the issue?

#Issue - 2

Also, Another issue is if i go to card payment and if i add some payment details  and continue and then if i press back without completing payment process. I come back to main screen and if i now again make payment using card successfully it doesn't give me any kind of callback(success, failure or external wallet). 

@ChintanAcharya  I think these are very heavy and serious issues which must be resolved very soon.

Thanks.

**Comment by singhbhavneet** [comment] 2019-11-13 11:31
Yeah these are some major issues. In my case I used their captured api to verify payment is made by user

**Comment by joshln87** [comment] 2019-12-02 08:28
Hi is there any update on this issue? Seems like the payment is still 'Captured' even when it's cancelled? Any workarounds?

**Comment by singhbhavneet** [comment] 2019-12-02 08:47
@joshln87 Have you tested same with live keys . I was having same issue but when I switched to live keys issue was solved itself

**Comment by shaikhriyaz434** [comment] 2020-03-20 17:45
i am facing same issues on test mode. Any update?

**Comment by kjdeepak** [comment] 2020-07-24 06:42
Is this expected behaviour in test mode?

**Comment by sumedht** [comment] 2020-10-21 09:29
We have fixed this issue. Try to update to our latest version if u have not. Closing this issue due to no further communication. Please feel free to either re-open the issue or create a new issue if you have any additional queries.

**Closed by sumedht** 2020-10-21 09:29 UTC
