### ISSUE TITLE
Module 'Razorpay' has no member named 'initWithKey'

### ISSUE THREAD

**Issue by carotkut94** [razorpay/razorpay-flutter#59] opened 2020-04-06 13:15 UTC
while running app on ios simulator or even on running on real device getting this issue
on xcode 11.0 with latest release of razorpay_flutter 1.1.2

razorpay_flutter-1.1.2/ios/Classes/RazorpayDelegate.swift:57:24: error: module 'Razorpay' has no member named
    'initWithKey'
            let razorpay = Razorpay.initWithKey(key ?? "", andDelegateWithData: self)

**Comment by shashikantshaale** [comment] 2020-04-07 18:37
I'm facing the same issue

**Comment by shashikantshaale** [comment] 2020-04-08 04:40
Duplicate of #57

**Comment by Nautiyalsachin** [comment] 2020-04-08 10:13
Hi @carotkut94 @shashikantshaale , we have published the new release v1.1.3 with the fix of this issue, please feel free to update your plugin and let us know how it's working for you. 

Closing this issue now, feel free to reopen it. 
Thanks!

**Closed by Nautiyalsachin** 2020-04-08 10:13 UTC
