### ISSUE TITLE
Please update library to support flutter version 3.19.6

### ISSUE THREAD

**Issue by YazadDuamasia** [razorpay/razorpay-flutter#381] opened 2024-05-08 06:08 UTC
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
Please update library to support newer flutter version 3.19.6. 

## Flutter Version :
Run `flutter version` in your terminal and copy the results here.
Flutter 3.19.6 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 54e66469a9 (3 weeks ago) • 2024-04-17 13:08:03 -0700
Engine • revision c4cd48e186
Tools • Dart 3.3.4 • DevTools 2.31.1

##Flutter build error
Try `flutter pub outdated` for more information.
The plugin `razorpay_flutter` doesn't have a main class defined in C:\Users\yazad\AppData\Local\Pub\Cache\hosted\pub.dev\razorpay_flutter-1.3.6\android\src\main\java\com\razorpay\razorpay_flutter\RazorpayFlutterPlugin.java or C:\Users\yazad\AppData\Local\Pub\Cache\hosted\pub.dev\razorpay_flutter-1.3.6\android\src\main\kotlin\com\razorpay\razorpay_flutter\RazorpayFlutterPlugin.kt. This is likely to due to an incorrect `androidPackage: com.razorpay.razorpay_flutter` or `mainClass` entry in the plugin's pubspec.yaml.
If you are the author of this plugin, fix the `androidPackage` entry or move the main class to any of locations used above. Otherwise, please contact the author of this plugin and consider using a different plugin in the meanwhile. 
Process finished with exit code 1

**Comment by traditionalwears** [comment] 2024-05-20 03:15
Hello, any update on this ??

**Comment by athul-getlead** [comment] 2024-05-22 06:34
stuck with the same issue, do you guys have any plans to update it.

**Comment by traditionalwears** [comment] 2024-05-26 06:30
I thinks its waste of time to depend on razorpay, such a horrible experience. There is no way to connect anyone for the support. I've been trying integrate the razorpay on flutter app, my app is in production still because of these issues with flutter plugin couldn't able to add to my app, and no one is responding.

**Comment by vivekshindhe** [comment] 2024-05-27 04:58
@YazadDuamasia @athul-getlead, This issue isn't reproducible by us even for versions flutter(3.22.0) and dart (3.4.0). Unsure if this issue is related to the flutter versioning. That said, found this on [StackOverflow](https://stackoverflow.com/questions/76845948/flutter-the-plugin-razorpay-flutter-doesnt-have-a-main-class-defined-in-c-u) that you can try. 

> Step 1. Go into this path C:\Users\Admin\AppData\Local\Pub\Cache\hosted\pub.dev\razorpay_flutter-1.3.5 AND delete this folder "razorpay_flutter-1 3.5" Step 2. In terminal run command "flutter clean" and "flutter Pub get"..

**Comment by vivekshindhe** [comment] 2024-05-27 05:51
@YazadDuamasia There is no specification for the razorpay-flutter package to not use 3.19.6 any flutter version above 2.0.0 can be used. As I mentioned, I tested this with 3.22.0.
Can you please share what error you are seeing?

**Comment by athul-getlead** [comment] 2024-05-27 13:10
A simple `flutter pub cache clean` solved the issue for me.

Thanks @vivekshindhe

**Comment by vivekshindhe** [comment] 2024-06-13 05:47
Closing this ticket. Please feel free to reply or open another ticket if there are any issues.

**Closed by vivekshindhe** 2024-06-13 05:47 UTC
