### ISSUE TITLE
App not getting compiled on Flutter 3.3.6

### ISSUE THREAD

**Issue by Manty-K** [razorpay/razorpay-flutter#281] opened 2022-10-31 10:08 UTC
## Description

App is not getting compiled on Flutter v3.3.6 |  razorpay_flutter v1.3.3.
Machine : Macbook Air (M1)

## Flutter Version :
3.3.6

## Steps To Reproduce

1. Create a new flutter project.
2. Add razorpay_flutter 1.3.3 to the ***pubspec.yaml*** file
3. run the flutter project

## Actual Results

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeDebugAssets'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve com.razorpay:checkout:1.6.+.
     Required by:
         project :app > project :razorpay_flutter
      > Failed to list versions for com.razorpay:checkout.
         > Unable to load Maven meta-data from https://jcenter.bintray.com/com/razorpay/checkout/maven-metadata.xml.
            > Could not HEAD 'https://jcenter.bintray.com/com/razorpay/checkout/maven-metadata.xml'.
               > Read timed out

## Expected Results
App should get compiled.

**Comment by webtamizhan** [comment] 2022-10-31 10:10
Duplicate of [#280](https://github.com/razorpay/razorpay-flutter/issues/280)

**Comment by vivekshindhe** [comment] 2022-11-03 10:19
Issue fixed on version 1.3.4(latest). Closing the issue for now. Please comment on open a new issue in case it persists

**Closed by vivekshindhe** 2022-11-03 10:19 UTC
