### ISSUE TITLE
Module compiled with Swift 5.0 cannot be imported by the Swift 5.1 compiler. SDK v1.1.2

### ISSUE THREAD

**Issue by raghav39** [razorpay/razorpay-flutter#38] opened 2019-10-16 03:57 UTC
Getting the following error In RazorpayDeligate.swift on the line:2
`Module compiled with Swift 5.0 cannot be imported by the Swift 5.1 compiler`

Already changed the podfile to include:
```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'YES'
      config.build_settings['SWIFT_VERSION'] = '5.1'
    end
  end
end

```

**Comment by LOG-TAG** [comment] 2019-10-20 07:03
what is the solution?

**Comment by MustansirZia** [comment] 2019-10-31 07:30
Duplicate of #28. 
As mentioned in #28, the issue can be fixed by updating the pub package to `1.1.2`. It was fixed in our case.

**Comment by sharad-paghadal** [comment] 2019-11-05 17:42
try this - https://pub.dev/packages/razorpay_plugin

**Comment by vikram94** [comment] 2020-05-21 20:24
Here is how I resolved the issue.. Hope helps someone and saves his time.

Put in Podfile - pod 'razorpay-pod', '1.1.5'
Delete Pod Folder
Put 'use_frameworks!' Below target ‘Runner’ do
Type Command in iOS - Pod update razorpay-pod
flutter pub pub cache repair
Flutter build iOS

in case of an issue do ask

**Closed** 2020-10-08 10:53 UTC
