### ISSUE TITLE
Exception in  com.razorpay.AutoReadOtpHelper

### ISSUE THREAD

**Issue by sanjaymajoka** [razorpay/razorpay-flutter#131] opened 2021-02-23 06:30 UTC
Hi we are using razorpay in our application but we have crashes in our applicaton due to razorpay AutoReadOtpHelper. This is very frequent crash in our application. We found this crash in firebase crashliytics.

Below is crash log:

Fatal Exception: java.lang.RuntimeException: Error receiving broadcast Intent { act=com.google.android.gms.auth.api.phone.SMS_RETRIEVED flg=0x200010 pkg=com.myapp.package (has extras) } in com.razorpay.AutoReadOtpHelper@2c9e11c
       at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1581)
       at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(-.java:2)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:233)
       at android.app.ActivityThread.main(ActivityThread.java:8010)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)

Caused by java.lang.NullPointerException
       at java.util.Objects.requireNonNull(Objects.java:220)
       at com.razorpay.AutoReadOtpHelper.onReceive(AutoReadOtpHelper.java:52)
       at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1566)
       at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(-.java:2)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:233)
       at android.app.ActivityThread.main(ActivityThread.java:8010)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)

**Comment by sumedht** [comment] 2021-03-01 05:39
@sanjaymajoka can u share version of Razorpay's flutter SDK ur using?

**Comment by sanjaymajoka** [comment] 2021-03-02 06:04
@sumedht  , We are using **razorpay_flutter: ^1.2.3**

**Comment by Nautiyalsachin** [comment] 2021-03-09 07:02
@sanjaymajoka Can you verify the integration steps which you followed again, also I would like to ask you to verify your plugin integration with our [sample app](https://github.com/razorpay/razorpay-flutter/tree/master/example). And still, if you are able to reproduce the issue then please create a sample app and share it here. So that we can debug it more. Thanks.

**Comment by sumedht** [comment] 2021-04-06 02:23
@sanjaymajoka Closing this issue as there is no further communication. Feel free to re-open if u still facing it.

**Closed by sumedht** 2021-04-06 02:23 UTC

**Comment by TheStarkster** [comment] 2021-11-02 17:20
im also facing this issue and im using **v1.2.7**
i followed every single step carefully (and there're not many steps anyway)
and below is the obvious code

```dart
class _WalletScreenState extends State<WalletScreen> {
  SharedPreferences _prefs;
  var _razorpay = Razorpay();

  @override
  void initState() {
    super.initState();
    _razorpay.on(Razorpay.EVENT_PAYMENT_SUCCESS, _handlePaymentSuccess);
    _razorpay.on(Razorpay.EVENT_PAYMENT_ERROR, _handlePaymentError);
    _razorpay.on(Razorpay.EVENT_EXTERNAL_WALLET, _handleExternalWallet);
  }

  @override
  void dispose() {
    _razorpay.clear();
    super.dispose();
  }

  void openCheckout() async {
    var options = {
      'key': '<MY_KEY>',
      'amount': 2000,
      'name': '<APP_NAME>',
      'description': '<DESCRIPTION>',
    };
    try {
      _razorpay.open(options);
    } catch (e) {
      debugPrint(e);
    }
  }

  void _handlePaymentSuccess(PaymentSuccessResponse response) async {
    // some business logic....
  }

  void _handlePaymentError(PaymentFailureResponse response) {
    // some business logic....
  }

  void _handleExternalWallet(ExternalWalletResponse response) async {
    // some business logic....
  }

```

i tried different versions too tried 1.2.6 & 1.2.3, why these version specifically? because i already integrated those versions in my previous projects and was working fine.

now the funny thing is all of those version above throwing different exceptions. which is making me doubt on razorpay's backend. Because few days back i saw razorpay admin panel going crazy because of some update, i even have the screenshot.
